### ISSUE TITLE
Error using jumpstart

### ISSUE THREAD

**Issue by PunkHaz4rd** [pepperhacking/robot-jumpstarter#1]
> $ py jumpstart.py service-tabletpage my-package-name MyServiceName
  File "jumpstart.py", line 66
    print "Renamed inside", filename

**Comment by EmileKroeger** [comment]
Sorry, what's the error here? (maybe you're using Python 3?)

**Comment by PunkHaz4rd** [comment]
Yes, I'm a clutz.
I didn't think through using `py` and not `python`.

Though changing it to make it work with python3 isn't so difficult. I just installed both version of pyhton in the end.
Sorry about that.
